import type { AboutHeroProps, ApproachStep, SectionHeaderProps } from '@/types/about';

type ApproachContent = {
  header: SectionHeaderProps;
  steps: ApproachStep[];
};

export const aboutContent: {
  hero: AboutHeroProps;
  approach: ApproachContent;
} = {
  hero: {
    eyebrow: 'About The Project',
    title: 'A research demo for AP and LA spine X-ray analysis',
    images: [
      {
        src: '/images/examples/ap/ap_pred.jpg',
        alt: 'Example AP overlay output generated by the project.',
        caption:
          'AP output shown from the repository demo assets. The AP flow returns an overlay, heatmap, and Cobb angle.',
      },
      {
        src: '/images/examples/la/la_pred.jpg',
        alt: 'Example lateral overlay output generated by the project.',
        caption:
          'Lateral output shown from the repository demo assets. The LA flow returns detections, average confidence, and an overlay image.',
      },
    ],
  },
  approach: {
    header: {
      eyebrow: 'How It Works',
      title: 'The live workflow maps directly to the code',
      description:
        'These steps describe the existing application flow, not an aspirational product roadmap.',
    },
    steps: [
      {
        title: 'Choose an AP or LA workflow',
        description:
          'The frontend exposes separate routes for AP and lateral spine X-rays so each view can use the correct backend model.',
        detail:
          'Users can either upload their own file or load one of the bundled example images from the demo gallery.',
      },
      {
        title: 'Upload a supported image',
        description:
          'The browser submits the file as multipart form data to /predict/ap or /predict/la.',
        detail:
          'The current dropzones accept PNG, JPG, and JPEG files up to 10 MB.',
      },
      {
        title: 'Run model-specific inference',
        description:
          'AP requests use the SpineNet-based pipeline, while LA requests use a YOLO model loaded from local weights.',
        detail:
          'Both flows write generated outputs into backend results directories before returning the response payload.',
      },
      {
        title: 'Render the returned outputs',
        description:
          'The frontend displays the original upload beside the generated overlay and the summary values returned by the backend.',
        detail:
          'AP currently highlights the Cobb angle and heatmap; LA shows detections and average confidence.',
        },
      ],
  },
};
